name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build ./app -t donation-app

    - name: Run container
      run: 
        docker run -d \
        -p 3000:3000 \
        -e MONGO_URL=monogdb://host.docker.internal:27017/donations \
        -e PORT=3000
        donation-app

    - name: Wait for app
      run: sleep 10

    - name: Test API
      run: curl http://localhost:3000
